#############################################################################
# Makefile for building: bin/fbblock
# Generated by qmake (2.01a) (Qt 4.8.4) on: Tue Sep 9 14:19:31 2014
# Project:  fbblock.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile fbblock.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -D_REENTRANT -Wall -W $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -D_REENTRANT -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I/usr/include/qt4/QtTest -Ibuild
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtTest -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = build/

####### Files

SOURCES       = main.cpp \
		fbblock.cpp \
		fbblocksolver.cpp \
		fbglobal.cpp \
		mda_io.cpp \
		fbparameterfile.cpp \
		fbsparsearray4d.cpp \
		fbsparsearray1d.cpp \
		fberrorestimator.cpp \
		fbtimer.cpp \
		nonlinearadjuster.cpp \
		mda.cpp \
		textfile.cpp 
OBJECTS       = build/main.o \
		build/fbblock.o \
		build/fbblocksolver.o \
		build/fbglobal.o \
		build/mda_io.o \
		build/fbparameterfile.o \
		build/fbsparsearray4d.o \
		build/fbsparsearray1d.o \
		build/fberrorestimator.o \
		build/fbtimer.o \
		build/nonlinearadjuster.o \
		build/mda.o \
		build/textfile.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qtestlib.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		fbblock.pro
QMAKE_TARGET  = fbblock
DESTDIR       = bin/
TARGET        = bin/fbblock

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: fbblock.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qtestlib.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtTest.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile fbblock.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/qtestlib.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtTest.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile fbblock.pro

dist: 
	@$(CHK_DIR_EXISTS) build/fbblock1.0.0 || $(MKDIR) build/fbblock1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) build/fbblock1.0.0/ && $(COPY_FILE) --parents fbblock.h arrays.h fbblocksolver.h fbglobal.h mda_io.h fbparameterfile.h fbsparsearray4d.h fbsparsearray1d.h fberrorestimator.h fbtimer.h nonlinearadjuster.h mda.h textfile.h build/fbblock1.0.0/ && $(COPY_FILE) --parents main.cpp fbblock.cpp fbblocksolver.cpp fbglobal.cpp mda_io.cpp fbparameterfile.cpp fbsparsearray4d.cpp fbsparsearray1d.cpp fberrorestimator.cpp fbtimer.cpp nonlinearadjuster.cpp mda.cpp textfile.cpp build/fbblock1.0.0/ && (cd `dirname build/fbblock1.0.0` && $(TAR) fbblock1.0.0.tar fbblock1.0.0 && $(COMPRESS) fbblock1.0.0.tar) && $(MOVE) `dirname build/fbblock1.0.0`/fbblock1.0.0.tar.gz . && $(DEL_FILE) -r build/fbblock1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

build/main.o: main.cpp fbtimer.h \
		arrays.h \
		fbsparsearray4d.h \
		fbsparsearray1d.h \
		mda_io.h \
		fbblocksolver.h \
		fbglobal.h \
		textfile.h \
		fberrorestimator.h \
		fbblock.h \
		nonlinearadjuster.h \
		fbparameterfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/main.o main.cpp

build/fbblock.o: fbblock.cpp fbblock.h \
		arrays.h \
		fbsparsearray4d.h \
		fbsparsearray1d.h \
		nonlinearadjuster.h \
		fbglobal.h \
		textfile.h \
		fbtimer.h \
		mda_io.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/fbblock.o fbblock.cpp

build/fbblocksolver.o: fbblocksolver.cpp fbblocksolver.h \
		fbglobal.h \
		textfile.h \
		arrays.h \
		fbsparsearray4d.h \
		fbsparsearray1d.h \
		fberrorestimator.h \
		fbblock.h \
		nonlinearadjuster.h \
		mda_io.h \
		fbtimer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/fbblocksolver.o fbblocksolver.cpp

build/fbglobal.o: fbglobal.cpp fbglobal.h \
		textfile.h \
		arrays.h \
		fbsparsearray4d.h \
		fbsparsearray1d.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/fbglobal.o fbglobal.cpp

build/mda_io.o: mda_io.cpp mda_io.h \
		arrays.h \
		fbsparsearray4d.h \
		fbsparsearray1d.h \
		mda.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/mda_io.o mda_io.cpp

build/fbparameterfile.o: fbparameterfile.cpp fbparameterfile.h \
		fbblocksolver.h \
		fbglobal.h \
		textfile.h \
		arrays.h \
		fbsparsearray4d.h \
		fbsparsearray1d.h \
		fberrorestimator.h \
		fbblock.h \
		nonlinearadjuster.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/fbparameterfile.o fbparameterfile.cpp

build/fbsparsearray4d.o: fbsparsearray4d.cpp fbsparsearray4d.h \
		fbsparsearray1d.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/fbsparsearray4d.o fbsparsearray4d.cpp

build/fbsparsearray1d.o: fbsparsearray1d.cpp fbsparsearray1d.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/fbsparsearray1d.o fbsparsearray1d.cpp

build/fberrorestimator.o: fberrorestimator.cpp fberrorestimator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/fberrorestimator.o fberrorestimator.cpp

build/fbtimer.o: fbtimer.cpp fbtimer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/fbtimer.o fbtimer.cpp

build/nonlinearadjuster.o: nonlinearadjuster.cpp nonlinearadjuster.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/nonlinearadjuster.o nonlinearadjuster.cpp

build/mda.o: mda.cpp mda.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/mda.o mda.cpp

build/textfile.o: textfile.cpp textfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/textfile.o textfile.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

